### ISSUE TITLE
RTC keeps "eating" batteries, help needed!

### ISSUE THREAD

**Issue by Turrican3** [screwbreaker/OpenA1200RTC#1]
Hey there,

my OpenA1200 RTC is literally eating batteries (i.e. a brand new 2032 only lasts a few days at best), but since I'm not very good (yet) at electronics, I'm kindly asking for help to solve this issue.

By the way I can send pictures of the assembled PCB if needed. The PCB itself has been manufactured by PCBway some time ago, but I was only able to solder everything together very recently.

Best regards and thanks for this awesome project!

**Comment by screwbreaker** [comment]
It's definitely not normal. Maybe you have a faulty clock chip. This stuff is very old, is possible that some of them are bad.
Or, if you have a socket, try without the clock IC, if the battery still dying there is something wrong on the PCB.

**Comment by Turrican3** [comment]
Thanks!

I ended up reflowing the socket and using a different chip (I had purchased a lot on AliExpress so I had plenty of spares) and it worked as expected, ditto for another two or three that I assembled afterwards.

So it's all good!
Best regards
